# Значения для деплоймента по умолчанию

# Значения для контейнеров
container:
  image    : "nginx"                  # Образ приложения
  tag      : "latest"                 # Версия образа
  appPort  : 80                       # Порт приложения
  probePort: 5678                     # Порт Probes
  readinessDelaySeconds : 12          # Период секунд между запуском контейнера и первой проверкой готовности принимать трафик
  readinessPeriodSeconds: 10          # Период секунд между каждой проверкой готовности принимать трафик
  livenessDelaySeconds  : 20          # Период секунд между запуском контейнера и первой проверкой функциональности контейнера
  livenessPeriodSeconds : 10          # Период секунд между каждой проверкой функциональности контейнера
  
# Лимиты и запросы ресурсов для контейнеров
resources:
  cpuLimits     : "400m"              # Повышенный лимит в 400m CPU для первых запросов приложения 
  memoryLimits  : "128Mi"             # Лимит использования памяти
  cpuRequests   : "100m"              # Запрос на резервирование CPU
  memoryRequests: "128Mi"             # Запрос на резервирование памяти

# Автоскейлинг для деплоймента
hpa:
  minReplicas : 2                     # Мин.  количество реплик     
  maxReplicas : 4                     # Макс. количество реплик
  targetCPU   : 85                    # Значение утилизации CPU, при достижении которого начнется запуск новых реплик
  targetMemory: 85                    # Значение утилизации памяти, при достижении которого начнется запуск новых реплик

# Значения для сервиса
service:
  type    : LoadBalancer              # Тип сервиса
  port    : 6789                      # Порт сервиса
  protocol: TCP                       # Протокол сервиса
