apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    app  : {{ .Release.Name }}-deployment
    env  : test
    owner: IvanGlyz
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:    
      affinity:
        podAntiAffinity:                         
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app                                 # Ключ antiAffinity 
                  operator: In                             # 
                  values:                                  #
                - {{ .Release.Name }}-web-app              # И значение ключа, по которым antiAffinity будет определять куда предпочтительно не назначать поды
              topologyKey: kubernetes.io/zone              # Топологический ключ для распределения подов по зонам
    spec:
      containers:
        - name : {{ .Release.Name }}-container
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          resources:
            limits:
              cpu   : {{ .Values.resources.cpuLimits }}
              memory: {{ .Values.resources.memoryLimits }}
            requests:
              cpu   : {{ .Values.resources.cpuRequests }}
              memory: {{ .Values.resources.memoryRequests }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.container.probePort }}
            periodSeconds      : {{ .Values.container.livenessPeriodSeconds }}
            initialDelaySeconds: {{ .Values.container.livenessDelaySeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.probePort }}
            periodSeconds      : {{ .Values.container.readinessPeriodSeconds }}
            initialDelaySeconds: {{ .Values.container.readinessDelaySeconds }}
